# Generated by Django 6.0.6 on 2026-06-22 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cantidad', models.CharField(default='0', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(default='Unidad', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('imagen', models.TextField(blank=True, default='default.png', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('rol_numero', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.CharField(max_length=100, verbose_name='Cantidad necesaria')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.ingrediente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.ManyToManyField(related_name='productos', through='usuarios_app.ProductoIngrediente', to='usuarios_app.ingrediente'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.CharField(blank=True, default='default.png', max_length=255, null=True)),
                ('contrasenia', models.CharField(max_length=255)),
                ('rol', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios_app.rol')),
            ],
        ),
    ]
