# Generated by Django 6.0.6 on 2026-06-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.TextField(blank=True, default='default.png', null=True),
        ),
    ]
